---
language: python

python:
    - "3.5"

sudo: false

services:
    - mongodb

script:
    - py.test tests/

install:
    - pip install -r requirements.txt .
    - mongo --version

notifications:
    email: false