language: python
cache: pip
services: mongodb
python:
  - "3.6.2"
  - "3.7.1"
  - "3.8"
env:
  - PIP=9.0.1 TRAVIS=1
  - PIP=18.1 TRAVIS=1
  - PIP=19.3.1 TRAVIS=1

install:
    - pip install cython
    - pip install -r requirements.txt -r requirements-dev.txt -e .

script: py.test --cov=scout -rxs tests/

notifications:
    email: false
