
language: python

python:
    - "3.5"

sudo: true
services:
    - mongodb
addons:
	apt:
		sources:
			- mongodb-3.4-precise
		packages:
			- mongodb-org-server
		
script:
    - py.test tests/

install:
    - pip install -r requirements.txt .
    - mongo --version

notifications:
    email: false