---
language: python

python:
    - "3.5"

sudo: required

services:
    - mongodb

script:
    - py.test tests/

addons:
    apt:
        sources:
            - mongodb-3.2-precise
        packages:
            - mongodb-org-server

install:
    - pip install -r requirements.txt .
    - mongo --version

notifications:
    email: false