---
language: python

python:
    - "3.6"

env:
    - TRAVIS=1 PIP=9.0.1

services:
    - mongodb

script:
    - py.test --cov=scout -rxs tests/

install:
	- pip install pip==$PIP
    - pip install cython
    - pip install -r requirements.txt -r requirements-dev.txt -e .

after_success:
    - coveralls

notifications:
    email: false
