
language: python

python:
    - "3.5"

services:
    - mongodb

script:
    - mongod --fork --logpath /dev/null --setParameter textSearchEnabled=true
    - py.test tests/

install:
    - pip install -r requirements.txt .
    - mongo --version

notifications:
    email: false