---
- name: install default dependencies
  pip: name={{ item }} state=latest
  with_items:
    - pip
    - pytest
    - ipython

- name: install package for development
  shell: pip install --editable .
  args:
    chdir: /vagrant

- name: install dev dependencies
  pip: requirements=/vagrant/requirements/dev.txt
